### ISSUE TITLE
Would love to see this as a BitBar plugin.

### ISSUE THREAD

**Issue by matryer** [carlmjohnson/pomodoro#1]
See https://getbitbar.com/

**Comment by earthboundkid** [comment]
I don't think this script would be suitable for BitBar. AFAICT, BitBar handles varying output by calling its plugin scripts periodically, so that in this case, the pomodoro plugin would need to be relaunched every second during the countdown, and it would need to remember where it was in countdown during the relaunch process. That would require a totally different architecture with the target time being saved somewhere (a dot file in ~?) and then accessed on startup.

One thing I have thought about is integrating OS X notification center alerts, but only as a way of showing the final "alert bell", not as a countdown. Probably the easiest way to do that though is just to do `pomodoro && script-that-does-notification-center` with some other existing script (e.g. [py](https://github.com/jacobsalmela/NCutil), [go](https://github.com/deckarep/gosx-notifier)).
